### ISSUE TITLE
Lỗi crawl

### ISSUE THREAD

**Issue by HardCore-spz** [alanpmk/crawl-vivawebtech-theme#1]
![image](https://github.com/alanpmk/crawl-vivawebtech-theme/assets/73431662/a7ec943e-efaa-4ef1-a3db-dc97194823ea)
Crawl không chạy, load lâu lắm

**Comment by alanpmk** [comment]
> ![image](https://user-images.githubusercontent.com/73431662/244927193-a7ec943e-efaa-4ef1-a3db-dc97194823ea.png) Crawl không chạy, load lâu lắm

Đã fix nhé.
